// GENERATED by tools/gen_quest_sources.py - do not edit by hand. Recipe scroll id -> quests that reward it.
package modules.recipebook;

final class QuestSources
{
	/** Rows are {scrollId, questId}; quest names are in {@link #NAMES}. */
	static final int[][] REWARDS =
	{
		{ 2353, 663 },
		{ 3023, 221 },
		{ 3024, 216 },
		{ 3025, 216 },
		{ 3838, 503 },
		{ 4963, 647 },
		{ 4963, 663 },
		{ 4967, 663 },
		{ 4972, 647 },
		{ 5000, 663 },
		{ 5001, 663 },
		{ 5002, 663 },
		{ 5004, 663 },
		{ 5005, 663 },
		{ 5006, 663 },
		{ 5007, 663 },
		{ 5348, 375 },
		{ 5350, 375 },
		{ 5352, 375 },
		{ 5364, 358 },
		{ 5366, 358 },
		{ 6329, 358 },
		{ 6331, 358 },
		{ 6333, 358 },
		{ 6335, 358 },
		{ 6337, 358 },
		{ 6339, 358 },
		{ 6847, 621 },
		{ 6847, 622 },
		{ 6847, 623 },
		{ 6849, 621 },
		{ 6849, 622 },
		{ 6849, 623 },
		{ 6851, 621 },
		{ 6851, 622 },
		{ 6851, 623 },
		{ 6881, 617 },
		{ 6881, 619 },
		{ 6883, 617 },
		{ 6883, 619 },
		{ 6885, 617 },
		{ 6885, 619 },
		{ 6887, 617 },
		{ 6887, 619 },
		{ 6891, 617 },
		{ 6891, 619 },
		{ 6893, 617 },
		{ 6893, 619 },
		{ 6895, 617 },
		{ 6895, 619 },
		{ 6897, 617 },
		{ 6897, 619 },
		{ 6899, 617 },
		{ 6899, 619 },
		{ 7580, 617 },
		{ 7580, 619 },
		{ 8690, 642 },
		{ 8692, 642 },
		{ 8694, 642 },
		{ 8696, 642 },
		{ 8698, 642 },
		{ 8700, 642 },
		{ 8702, 642 },
		{ 8704, 642 },
		{ 8706, 642 },
		{ 8708, 642 },
		{ 8710, 642 },
	};

	static final String[][] NAMES =
	{
		{ "216", "Trial Of The Guildsman" },
		{ "221", "Testimony Of Prosperity" },
		{ "358", "Illegitimate Child Of The Goddess" },
		{ "375", "Whisper Of Dreams Part 2" },
		{ "503", "Pursuit Of Clan Ambition" },
		{ "617", "Gather The Flames" },
		{ "619", "Relics Of The Old Empire" },
		{ "621", "Egg Delivery" },
		{ "622", "Specialty Liquor Delivery" },
		{ "623", "The Finest Food" },
		{ "642", "APowerful Primeval Creature" },
		{ "647", "Influx Of Machines" },
		{ "663", "Seductive Whispers" },
	};

	/** Rows are {questId, startNpcId}: the NPC that hands the quest out (first one when there are several). */
	static final int[][] STARTS =
	{
		{ 216, 30103 },
		{ 221, 30104 },
		{ 358, 30862 },
		{ 375, 30515 },
		{ 503, 30760 },
		{ 617, 31539 },
		{ 619, 31538 },
		{ 621, 31521 },
		{ 622, 31521 },
		{ 623, 31521 },
		{ 642, 32105 },
		{ 647, 32069 },
		{ 663, 30846 },
	};

	private QuestSources()
	{
	}
}
