#!/usr/bin/env python3
"""Regenerates scripts/QuestSources.java: which quests hand out which recipe scrolls.

Run from the game folder:  python3 tools/gen_quest_sources.py <path to game/data> > scripts/QuestSources.java
Reads data/Recipes.xml for the recipe scroll ids and scans data/scripts/quests/**/*.java for reward calls
(giveItems / rewardItems / addItem second argument, and `new ItemHolder(id, ...)`), resolving int constants and
int[] arrays declared in the same file.
"""
import re, sys, glob, os, collections

data = sys.argv[1] if len(sys.argv) > 1 else "."
scrolls = {int(x) for x in re.findall(r'recipeId="(\d+)"', open(os.path.join(data, "Recipes.xml"), encoding="utf-8").read())}
call = re.compile(r'\b(giveItems|rewardItems|addItem|giveItem)\s*\(')
found = collections.defaultdict(set)
starts = collections.defaultdict(list)  # questId -> start NPC ids (from addStartNpc)

def split_top(args):
    out, depth, cur = [], 0, ""
    for ch in args:
        if ch in "({[": depth += 1
        elif ch in ")}]": depth -= 1
        if ch == "," and depth == 0:
            out.append(cur); cur = ""
        else:
            cur += ch
    out.append(cur)
    return out

def pretty(folder):
    m = re.match(r'Q(\d+)_(.+)', folder)
    qid, name = int(m.group(1)), m.group(2)
    name = re.sub(r'(?<=[a-z])(?=[A-Z])|(?<=[A-Za-z])(?=\d)', ' ', name)
    return qid, name

for f in sorted(glob.glob(os.path.join(data, "scripts", "quests", "**", "*.java"), recursive=True)):
    folder = os.path.basename(os.path.dirname(f))
    if not re.match(r'Q\d+_', folder):
        folder = os.path.basename(f)[:-5]
        if not re.match(r'Q\d+_', folder):
            continue
    t = open(f, encoding="utf-8", errors="ignore").read()
    consts = {}
    for m in re.finditer(r'\b(?:int|Integer)\s+(\w+)\s*=\s*(\d+)\s*;', t):
        consts[m.group(1)] = [int(m.group(2))]
    for m in re.finditer(r'\bint\[\]\s+(\w+)\s*=\s*\{([^}]*)\}', t, re.S):
        consts[m.group(1)] = [int(x) for x in re.findall(r'\d+', m.group(2))]
    def ids_of(tokens):
        for tok in tokens:
            for x in ([int(tok)] if tok.isdigit() else consts.get(tok, [])):
                if x in scrolls:
                    found[x].add(pretty(folder))
    for m in call.finditer(t):
        i, d, j = m.end(), 1, m.end()
        while j < len(t) and d > 0:
            d += (t[j] == '(') - (t[j] == ')'); j += 1
        parts = split_top(t[i:j - 1])
        if len(parts) > 1:
            ids_of(re.findall(r'\b\w+\b', parts[1]))
    qid_here = pretty(folder)[0]
    for m in re.finditer(r'\baddStartNpc\s*\(([^)]*)\)', t):
        for tok in re.findall(r'\b\w+\b', m.group(1)):
            for x in ([int(tok)] if tok.isdigit() else consts.get(tok, [])):
                if x not in starts[qid_here]:
                    starts[qid_here].append(x)
    for m in re.finditer(r'new ItemHolder\(\s*(\w+)\s*,', t):
        ids_of([m.group(1)])

print("// GENERATED by tools/gen_quest_sources.py - do not edit by hand. Recipe scroll id -> quests that reward it.")
print("package modules.recipebook;\n\nfinal class QuestSources\n{")
print("\t/** Rows are {scrollId, questId}; quest names are in {@link #NAMES}. */")
print("\tstatic final int[][] REWARDS =\n\t{")
rows = []
names = {}
for sid in sorted(found):
    for qid, name in sorted(found[sid]):
        rows.append("\t\t{ %d, %d }," % (sid, qid)); names[qid] = name
print("\n".join(rows))
print("\t};\n")
print("\tstatic final String[][] NAMES =\n\t{")
for qid in sorted(names):
    print('\t\t{ "%d", "%s" },' % (qid, names[qid].replace('"', '')))
print("\t};\n")
print("\t/** Rows are {questId, startNpcId}: the NPC that hands the quest out (first one when there are several). */")
print("\tstatic final int[][] STARTS =\n\t{")
for qid in sorted(names):
    if starts.get(qid):
        print("\t\t{ %d, %d }," % (qid, starts[qid][0]))
print("\t};\n\n\tprivate QuestSources()\n\t{\n\t}\n}")
