#!/usr/bin/env python3
"""Regenerates scripts/QuestData.java from the quest scripts.

Run:  python3 tools/gen_quest_data.py <path to game/data> > scripts/QuestData.java
Reads data/scripts/quests/Q*/Q*.java. For each quest it records the id, script name, client name (the super() call),
minimum level (first getLevel() check or MIN_LEVEL constant), start NPCs (addStartNpc), kill targets (addKillId),
reward items (giveItems/rewardItems whose item is not a registered quest item), and the largest exp/sp reward.
Everything is read from source text, so treat levels and rewards as a guide, not gospel.
"""
import re, sys, glob, os

data = sys.argv[1] if len(sys.argv) > 1 else "."

def split_top(args):
    out, depth, cur = [], 0, ""
    for ch in args:
        if ch in "({[": depth += 1
        elif ch in ")}]": depth -= 1
        if ch == "," and depth == 0:
            out.append(cur); cur = ""
        else:
            cur += ch
    out.append(cur)
    return out

def call_args(t, name):
    for m in re.finditer(r'\b' + name + r'\s*\(', t):
        i, d, j = m.end(), 1, m.end()
        while j < len(t) and d > 0:
            d += (t[j] == '(') - (t[j] == ')'); j += 1
        yield split_top(t[i:j - 1])

rows = []
for f in sorted(glob.glob(os.path.join(data, "scripts", "quests", "Q*", "Q*.java"))):
    script = os.path.basename(f)[:-5]
    if not re.match(r'Q\d+_', script):
        continue
    t = open(f, encoding="utf-8", errors="ignore").read()
    sm = re.search(r'super\(\s*(\d+)\s*,\s*"([^"]*)"', t)
    if not sm:
        continue
    qid, name = int(sm.group(1)), sm.group(2)

    consts = {}
    for m in re.finditer(r'\b(?:int|Integer)\s+(\w+)\s*=\s*(-?\d+)\s*;', t):
        consts[m.group(1)] = [int(m.group(2))]
    for m in re.finditer(r'\bint\[\]\s+(\w+)\s*=\s*\{([^}]*)\}', t, re.S):
        consts[m.group(1)] = [int(x) for x in re.findall(r'\d+', m.group(2))]

    def ids(tokens):
        out = []
        for tok in tokens:
            for x in ([int(tok)] if tok.isdigit() else consts.get(tok, [])):
                out.append(x)
        return out

    def ids_arg(arg):
        return ids(re.findall(r'\b\w+\b', arg))

    starts = []
    for a in call_args(t, 'addStartNpc'):
        for x in ids_arg(",".join(a)):
            if x not in starts: starts.append(x)
    kills = []
    for a in call_args(t, 'addKillId'):
        for x in ids_arg(",".join(a)):
            if x not in kills: kills.append(x)
    qitems = set()
    for a in call_args(t, 'registerQuestItems'):
        qitems.update(ids_arg(",".join(a)))

    # Minimum level: MIN_LEVEL-style constant, else the first "getLevel() < N" / ">= N" check.
    lvl = 0
    m = re.search(r'\b(?:MIN_LEVEL|MIN_LVL|MINIMUM_LEVEL)\s*=\s*(\d+)', t)
    if m:
        lvl = int(m.group(1))
    else:
        m = re.search(r'getLevel\(\)\s*(<|>=)\s*(\d+)', t)
        if m:
            lvl = int(m.group(2))
    if not (0 < lvl <= 85):
        lvl = 0

    rewards = {}
    for fn in ('giveItems', 'rewardItems'):
        for a in call_args(t, fn):
            if len(a) < 3: continue
            item = ids_arg(a[1])
            cnt = a[2].strip()
            n = int(cnt) if cnt.isdigit() else 0
            if len(item) == 1 and item[0] not in qitems:
                rewards[item[0]] = max(rewards.get(item[0], 0), n)
    exp = sp = 0
    for a in call_args(t, 'addExpAndSp'):
        if len(a) >= 3 and a[1].strip().isdigit() and a[2].strip().isdigit():
            if int(a[1]) > exp: exp, sp = int(a[1]), int(a[2])

    # Repeatable: a quest that can only ever be left with exitQuest(true...) can be taken again.
    exits = [a[0].strip() for a in call_args(t, 'exitQuest')]
    if any(e == 'false' for e in exits): rep = 0
    elif any(e == 'true' for e in exits): rep = 1
    else: rep = 2  # unknown
    if 'extends AbstractSagaQuest' in t:  # class-change sagas keep their data in _npc/_mob arrays; the base class sets level 76
        nm = re.search(r'_npc\s*=\s*new int\[\]\s*\{([^}]*)\}', t, re.S)
        if nm and not starts:
            starts = [int(x) for x in re.findall(r'\d+', nm.group(1))[:1]]
        mm = re.search(r'_mob\s*=\s*new int\[\]\s*\{([^}]*)\}', t, re.S)
        if mm and not kills:
            kills = [int(x) for x in re.findall(r'\d+', mm.group(1))]
        lvl, rep = (lvl or 76), 0
    rows.append((qid, script, name, lvl, rep, starts, kills[:40], sorted(rewards.items())[:12], exp, sp))

rows.sort()
print("// GENERATED by tools/gen_quest_data.py - do not edit by hand.")
print("package modules.questbook;\n")
print("final class QuestData\n{")
print("\t/** {id, script name, client name, min level, repeatable (0 no, 1 yes, 2 unknown), start npcs, kill npcs, rewards as item:count, exp, sp} */")
print("\tstatic final String[][] ROWS =\n\t{")
for qid, script, name, lvl, rep, starts, kills, rewards, exp, sp in rows:
    print('\t\t{ "%d", "%s", "%s", "%d", "%d", "%s", "%s", "%s", "%d", "%d" },' % (
        qid, script, name.replace('"', ''), lvl, rep, ",".join(map(str, starts)), ",".join(map(str, kills)),
        ",".join("%d:%d" % r for r in rewards), exp, sp))
print("\t};\n\n\tprivate QuestData()\n\t{\n\t}\n}")
