#!/usr/bin/env python3
"""Reads dist/game/data/PhantomPopulations.xml (the server's named hunting grounds) and writes scripts/FarmingGroundData.java:
every hunting ground's circles, flattened. Usage: python3 tools/gen_farming_grounds.py path/to/PhantomPopulations.xml"""
import re, sys
t = open(sys.argv[1], encoding='utf-8').read()
rows = re.findall(r'<population name="([^"]*)" x="(-?\d+)" y="(-?\d+)" z="-?\d+" radius="(\d+)"', t)
c = sorted({(int(x), int(y), int(r)) for n, x, y, r in rows if 'Quest' not in n})
body = ',\n'.join('\t\t' + ', '.join(str(v) for v in tri) for tri in c)
java = '''package modules.phantomencounters;

/** GENERATED by tools/gen_farming_grounds.py from PhantomPopulations.xml: do not edit. x, y, radius for every hunting ground circle. */
final class FarmingGroundData
{
	static final int[] CIRCLES =
	{
%s
	};

	private FarmingGroundData()
	{
	}
}
''' % body
open('scripts/FarmingGroundData.java', 'w', encoding='utf-8').write(java)
print(len(c), 'circles')
