#!/usr/bin/env python3
"""Reads dist/game/data/PhantomPopulations.xml (the server's named hunting grounds) and writes scripts/GroundData.java.
Usage: python3 tools/gen_ground_data.py path/to/PhantomPopulations.xml"""
import re, sys, collections
src = sys.argv[1]
t = open(src, encoding='utf-8').read()
rows = re.findall(r'<population name="([^"]*)" x="(-?\d+)" y="(-?\d+)" z="(-?\d+)" radius="(\d+)" count="\d+" minLevel="(\d+)" maxLevel="(\d+)"', t)
g = collections.OrderedDict()
for n, x, y, z, r, a, b in rows:
    if 'Quest' in n:
        continue
    d = g.setdefault(n, {'min': 999, 'max': 0, 'c': set()})
    d['min'] = min(d['min'], int(a)); d['max'] = max(d['max'], int(b))
    d['c'].add((int(x), int(y), int(r)))
out = []
for n, d in sorted(g.items(), key=lambda kv: (kv[1]['min'], kv[0])):
    slug = re.sub(r'[^a-z]', '', n.lower())
    circles = ','.join('%d,%d,%d' % c for c in sorted(d['c']))
    out.append('\t\t{ "%s", "%s", "%d", "%d", "%s" },' % (slug, n, d['min'], d['max'], circles))
java = '''package modules.hunting;

/** GENERATED by tools/gen_ground_data.py from PhantomPopulations.xml: do not edit. {slug, name, minLevel, maxLevel, "x,y,r,x,y,r..."} */
final class GroundData
{
	static final String[][] ROWS =
	{
%s
	};

	private GroundData()
	{
	}
}
''' % '\n'.join(out)
open('scripts/GroundData.java', 'w', encoding='utf-8').write(java)
print(len(out), 'grounds')
